# ***************************************************************************************
# ***************************************************************************************
#
#      Name :      makelogo.py
#      Authors :   Paul Robson (paul@robsons.org.uk)
#      Date :      26th December 2024
#      Purpose :   Create the Olimex Logo
#
# ***************************************************************************************
# ***************************************************************************************

import sys,os,re
from PIL import Image

image = Image.open("olimex.png")

width = image.size[0]
height = image.size[1]
widthBytes = (width + 7) >> 3

logoData = [ 0 ] * (height * widthBytes)

for x in range(0,width):
	for y in range(0,height):
		colour = image.getpixel((x,y))
		isOn = (colour[0]+colour[1]+colour[2]) != 0
		if isOn:
			logoData[y*widthBytes+(x >> 3)] |= 0x80 >> (x & 7)

print("//\n//\tThis file is automatically generated\n//")
print("#define LOGO_WIDTH_BYTES {0}".format(widthBytes))
print("#define LOGO_HEIGHT {0}".format(height))
print("static const uint8_t logoData[] = {")
print(",".join([str(x) for x in logoData]))
print("};")